baseURL = "/"
title = "Levent Bekdemir"
theme = "spectre-pixel-theme"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/lvntbkdmr/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/leventbekdemir/"},
      {Name = "HackerRank", URL = "https://www.hackerrank.com/lvntbkdmr/"}
  ]

[params]
  description = "I used to be an adventurer like you.."